### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by asood123** [AngularLovers/Angular2#15]
Hi there - 

I'm one of the founders of Open Collective. I saw that you applied to join Open Collective - thanks!

I'm wondering what you plan to use the funds for and whether you are expecting donations to be in USD.

Thanks
Aseem

**Comment by xiaomoinfo** [comment]
dollor or rmb

**Comment by asood123** [comment]
Hi Peng - This would be in dollars. We don't support RMB yet.

**Comment by xiaomoinfo** [comment]
@asood123 dollars is ok
