### ISSUE TITLE
请移除电子书

### ISSUE THREAD

**Issue by asnowwolf** [AngularLovers/angular2#7]
很高兴看到你们对ng2的热情。对社区做出贡献的方式有很多，但上传电子书不是好办法。请删除“电子书”目录下的内容。
我是Angular中文社区的雪狼，我们和作者以及图灵共同合作的ng-book2中文版即将出版，届时会有很多推广活动。
如果感兴趣，请加我微信asnowwolf，我们可以共同为这个技术社区做贡献。

**Comment by syoubaku** [comment]
@asnowwolf  不好意思，以前的分支忘了移除
